insert into user (name, lastname, address, paymentmethod) values ('Erna', 'Witcomb', '02 New Castle Terrace', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Aguistin', 'Stoter', '13417 Moose Way', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Cassi', 'Glantz', '19 Petterle Street', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Bili', 'Hattam', '3797 Burning Wood Alley', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Kalila', 'Bazoge', '930 Forest Run Avenue', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Jewelle', 'Lawden', '4078 Packers Way', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Hedy', 'Goldup', '6 Dryden Court', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Jewell', 'Colquhoun', '233 Shopko Terrace', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Tallulah', 'Chessun', '4994 Bunker Hill Lane', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Kordula', 'Tribell', '8 Morningstar Parkway', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Haroun', 'Goodred', '711 Corben Way', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Benjamin', 'Alston', '014 New Castle Alley', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Dew', 'Parzizek', '32 Hermina Place', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Lorne', 'Dedon', '53630 Sachs Place', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Delmor', 'Vero', '1 Sutteridge Trail', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Valencia', 'Cartmail', '787 Village Green Trail', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Amil', 'Collecott', '3 Bunting Way', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Sher', 'Joddins', '61505 Waxwing Point', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Loren', 'Wrigglesworth', '11 Ruskin Junction', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Lorrie', 'Harmeston', '5229 Debra Avenue', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Leon', 'Extall', '7 Coleman Road', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Thadeus', 'Wisedale', '8 Bunker Hill Plaza', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Trev', 'Giacobilio', '797 Autumn Leaf Parkway', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Tedd', 'Stoneman', '0 Vermont Plaza', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Daniel', 'Chittim', '09834 Rutledge Place', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Deeyn', 'Nickolls', '12869 Kropf Road', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Manolo', 'Jerromes', '6103 Autumn Leaf Hill', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Michael', 'Sidey', '7795 Buhler Trail', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Austina', 'Tisor', '2 Loomis Park', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Mycah', 'Cortese', '8 Canary Pass', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Pollyanna', 'Aronovich', '449 David Street', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Kasper', 'De Michele', '3 Haas Way', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Renaud', 'Farryn', '6 Cordelia Court', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Ethelred', 'End', '3 Browning Pass', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Mark', 'Breslane', '10 East Crossing', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Caddric', 'Koschek', '056 Leroy Crossing', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Miof mela', 'Touson', '46 Mcguire Center', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Jessalin', 'Balsellie', '49 Hollow Ridge Court', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Kary', 'Chivers', '572 Hanson Road', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Thatcher', 'Doutch', '46 Moose Court', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Giana', 'Smalman', '11 Hollow Ridge Terrace', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Jillana', 'Dashper', '4 Homewood Circle', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Bamby', 'Djorvic', '12496 Commercial Terrace', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Tracee', 'Pass', '1 Carberry Street', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Abelard', 'Jaeggi', '7 Eagan Place', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Arden', 'Fulger', '9896 Macpherson Alley', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Carmella', 'Adie', '13928 Arizona Avenue', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Minna', 'Wellings', '6 Atwood Alley', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Vachel', 'Garrold', '4965 Vidon Parkway', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Lissa', 'Glassup', '892 Kensington Point', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Ax', 'Cosgreave', '86 Mcguire Point', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Dasha', 'McIlraith', '894 Merrick Pass', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Bartram', 'McCrudden', '224 Monterey Center', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Berget', 'Biggerdike', '05004 Montana Circle', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Dyana', 'Smeeton', '7 Artisan Junction', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Janna', 'Laurant', '7184 Judy Parkway', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Bobby', 'Turone', '57 Atwood Court', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Annabal', 'Kettley', '7328 Maryland Drive', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Charisse', 'Sleney', '02 Jackson Road', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Cilka', 'Barradell', '535 American Park', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Dell', 'Shotbolt', '584 Mifflin Point', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Gayle', 'Duer', '68 Westridge Road', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Colan', 'Falkous', '5 Drewry Way', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Felice', 'Gratton', '8 Mosinee Park', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Austen', 'Hoy', '11 West Crossing', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Manya', 'Smorthit', '743 Holmberg Junction', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Luca', 'Stoakes', '65944 Messerschmidt Hill', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Zachariah', 'Sieghart', '583 Morningstar Pass', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Holmes', 'Moss', '7 Daystar Center', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Bone', 'Sumers', '328 Springview Alley', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Mickie', 'Feldman', '91 Packers Park', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Erwin', 'Cheesman', '06 Cascade Junction', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Adella', 'Vasyutichev', '0 Evergreen Hill', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Joela', 'Dakhno', '00631 Anhalt Junction', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Deerdre', 'Peartree', '91 Hanson Parkway', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Rickie', 'Cartin', '34 Goodland Plaza', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Avery', 'Tuckett', '59325 Lawn Way', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Heriberto', 'Heigho', '2665 Almo Way', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Nial', 'MacMeekan', '9 Myrtle Avenue', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Lindsay', 'Von Der Empten', '53384 American Place', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Gusti', 'Rosenauer', '39172 Daystar Road', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Aaren', 'Scarre', '2440 Pierstorff Junction', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Mellisent', 'Worshall', '55 Dawn Point', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Seymour', 'Hulbert', '45018 Judy Drive', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Franzen', 'Ewells', '99 Green Ridge Circle', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Lynna', 'Spacy', '5931 Anniversary Alley', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Miof mela', 'Juste', '39493 Melody Lane', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Florence', 'Ivanishin', '59617 Corben Trail', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Sonja', 'Ren', '92 Sugar Junction', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Woodrow', 'Claridge', '7 Carioca Parkway', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Maxie', 'Kemmer', '4 Dayton Crossing', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Sunny', 'Behninck', '39 Eggendart Junction', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Braden', 'Nano', '04632 Steensland Drive', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Merna', 'Tregust', '617 Dunning Drive', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Isa', 'Caulket', '1341 Carioca Drive', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Micah', 'Primett', '53 Anhalt Hill', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Sharona', 'Rigney', '35 Coleman Street', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Leone', 'Ozelton', '4 David Place', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Ericka', 'Summers', '751 Michigan Court', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Allis', 'Stein', '29193 Bayside Road', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Cynthie', 'Edens', '3774 South Lane', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Hamlen', 'Kemmey', '79 Claremont Way', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Bernhard', 'Dunsire', '2020 Bultman Circle', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Briney', 'Brouncker', '94 School Road', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Gerianna', 'Ballard', '33569 Hauk Drive', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Jenny', 'Densham', '9 Jenifer Alley', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Lesli', 'Grigaut', '067 Haas Park', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Briny', 'Isacq', '4454 Schlimgen Lane', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Cyndia', 'Sommerton', '2 Graceland Drive', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Camilla', 'Giraudot', '5984 Fordem Way', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Carmelle', 'Reimers', '6 Transport Trail', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Dave', 'Keggins', '9 Ludington Lane', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Camellia', 'Mansel', '06 Dapin Plaza', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Samantha', 'Kimber', '128 Hudson Avenue', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Carly', 'Sarrell', '85 Maple Street', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Rhea', 'Gasticke', '64 Ramsey Road', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Kerr', 'Vaud', '026 Veith Way', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Justine', 'Argrave', '0943 Mallard Trail', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Sinclair', 'Pinnegar', '3 Myrtle Avenue', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Freddy', 'Elcoat', '0634 Granby Court', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Llywellyn', 'Simone', '42 Homewood Parkway', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Brianne', 'Ayshford', '49948 Meadow Vale Avenue', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Conchita', 'Ivantsov', '4189 Green Ridge Junction', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Glenn', 'Donaghie', '0658 Tony Trail', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Bobbee', 'Veillard', '74514 Westerfield Place', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Adam', 'Sallis', '2 Spenser Drive', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Bax', 'Rubie', '6607 Milwaukee Circle', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Raf', 'Roylance', '352 Shelley Court', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Benton', 'Chase', '05846 Algoma Terrace', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Meridel', 'Havick', '704 Marcy Center', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Craggy', 'Scoffham', '0 Lotheville Circle', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Harlene', 'Assard', '26 Boyd Alley', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Anet', 'Sparshatt', '69 Duke Point', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Lorenzo', 'Ruppele', '1391 Pierstorff Center', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Raven', 'Lawson', '969 Elmside Circle', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Adorne', 'Shaudfurth', '81312 Buena Vista Court', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Levey', 'Miche', '0139 Pennsylvania Plaza', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Florina', 'Kilday', '55 West Junction', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Philbert', 'Caudray', '24249 Roxbury Terrace', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Alphard', 'Entwistle', '7175 Mallard Alley', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Kelcy', 'Maric', '643 Dottie Pass', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Ray', 'Slott', '0431 Di Loreto Place', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Alessandro', 'Juhruke', '3466 Fairview Center', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Maurise', 'Lealle', '785 Vahlen Crossing', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Marleah', 'Bowler', '7 Lukken Place', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Roseanna', 'Drought', '832 Russell Terrace', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Richart', 'Antowski', '935 Morningstar Terrace', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Iris', 'Topley', '3 Eastlawn Street', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Gael', 'Rattrie', '6 Logan Avenue', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Bella', 'Paterson', '5020 Pearson Junction', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Adriena', 'Muirhead', '6788 Coolidge Hill', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Jocelyn', 'Meugens', '3 Haas Crossing', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Tobey', 'Bagg', '36858 Hoffman Park', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Sherill', 'Rodger', '2962 Westerfield Way', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Huntley', 'Brellin', '65545 Moose Parkway', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Ira', 'Sotheby', '9 Bay Road', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Benito', 'McEttigen', '0 Swallow Junction', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Koressa', 'Praundl', '3324 Pawling Junction', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Avie', 'McGeffen', '3 Vernon Drive', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Rora', 'Boog', '06 Carioca Trail', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Evaleen', 'Server', '38 Saint Paul Avenue', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Ramona', 'Chilton', '19 Waubesa Park', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Billy', 'Shilstone', '521 Grover Alley', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Warde', 'Cobbledick', '53815 Roth Place', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Devin', 'Halwell', '43687 Rusk Point', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Caron', 'Rowantree', '40948 Pennsylvania Place', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Courtney', 'Sponder', '53 Bartillon Way', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Brady', 'Seleway', '0621 Haas Terrace', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Stirling', 'Haydock', '57804 Butternut Way', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Jock', 'Pietrusiak', '49892 Clove Point', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Amelita', 'Moult', '3 Maryland Crossing', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Hayden', 'Colbert', '76 South Point', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Rowney', 'Cullin', '96321 Mendota Lane', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Camella', 'Brewster', '45324 Loeprich Alley', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Maryjo', 'Yokley', '89 Surrey Drive', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Joscelin', 'Michurin', '72208 Packers Street', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Graeme', 'Edgeon', '5 Hoepker Junction', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Vinni', 'Drescher', '38915 Mitchell Hill', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Paulie', 'Brenard', '832 Manley Terrace', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Erda', 'Howarth', '05869 Kings Pass', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Claudius', 'Adriaan', '4434 Starling Circle', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Sheila-kathryn', 'Fishly', '06 Nancy Circle', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Maighdiln', 'Deverill', '72 Beilfuss Terrace', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Henrik', 'Caff', '4 Pine View Parkway', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Alvie', 'Deyes', '2 Shoshone Terrace', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Max', 'Keysel', '7 Anthes Lane', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Joye', 'Henryson', '1 Jana Plaza', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Hersch', 'Coker', '227 3rd Drive', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Winna', 'Belderson', '48337 Dunning Alley', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Maury', 'Hinkens', '473 Cambridge Street', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Angel', 'Freyne', '8756 Armistice Road', 'VISA');
insert into user (name, lastname, address, paymentmethod) values ('Wallis', 'Doerrling', '0 Del Sol Plaza', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Carolus', 'Dealy', '5486 Autumn Leaf Court', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Alanson', 'Fforde', '0 Westend Junction', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Abdel', 'Prodrick', '793 Eagan Point', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Ax', 'Jarrette', '3764 Eastwood Parkway', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Aluino', 'Gaffon', '26853 Dryden Lane', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Manda', 'McDougal', '92753 Pankratz Terrace', 'PAYPAL');
insert into user (name, lastname, address, paymentmethod) values ('Sibyl', 'Hatherleigh', '24261 Garrison Alley', 'TRANSFERENCIA');
insert into user (name, lastname, address, paymentmethod) values ('Bartholemy', 'Cordingley', '481 Summer Ridge Court', 'PAYPAL');
